# SPDX-FileCopyrightText: 2024 Chris Rizzitello <sithlord48@gmail.com>
# SPDX-License-Identifier: MIT

name: "Fancy Checkout"
author: "@sithlord48"
description: "Checkout a repo with all the tags in one step"
branding:
  icon: 'check'
  color: 'green'

runs:
  using: "composite"

  steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0

    - name: Fetch tags
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        git fetch --tags --force
      shell: bash
